### ISSUE TITLE
Where can I find the embeddings files?

### ISSUE THREAD

**Issue by suhas-bn-1412** [Cynwell/Text-Level-GNN#1]
Can you upload those files too

**Comment by Cynwell** [comment]
Embeddings file are too large to be uploaded here. Instead, you can download it from the Standford NLP GloVe project website.

Embeddings file can be downloaded from this website: https://nlp.stanford.edu/projects/glove/
Or you can directly download the file via this link: http://nlp.stanford.edu/data/glove.6B.zip

Once you have finished downloading, extract the file and set up the directory as stated in README.md and it will work.
